---
- name: Copy some useful scripts
  copy:
    src: dig.sh
    #dest: /home/allan/dig.sh
    dest: "/home/{{ user_name }}/dig.sh"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755

