---
- name: Prepare resolv.conf for editing
  file:
    path: /etc/resolv.conf
    attributes: -i

- name: Modify /etc/resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    attributes: +i
    backup: yes

