---
# Create a user with admin privileges in order to avoid doing things
# directly as root.

- name: Create a new user with admin privileges
  user:
    name: "{{ admin_user_name }}"
    password: "{{ admin_user_password }}"
    comment: "{{ admin_user_comment }}"
    # NOTE:
    # 'group' sets the user's primary group; 
    # 'groups' sets additional groups.
    groups: "{{ admin_user_groups }}"
    append: yes
    create_home: yes
    state: present

- name: Allow users in the wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Send SSH public key 
  authorized_key:
    user: "{{ admin_user_name }}"
    state: present
    key: "{{ admin_user_public_key }}"

